# Key = existing
# Value = new

# The properties defined in this file are used by the 'rebrandProject' Gradle
# task to alter the branding of the project by editing packages, directories,
# files and file contents. The task is primarily intended to be run one time
# after generating a repo from the templated, though it can be used later if
# appropriate consideration is given to potential conflicts.

# Properties must be ordered so that renames do not interfere.
# For example, placing
# 'OwnerName=NewName'
# before
# 'OwnerName/Repo=NewName/NewRepo'
# would cause the first operation to rename occurrences of 'OwnerName/Repo' to
# 'NewName/Repo', meaning the second key would no longer match.

# Even if you are confident that the operation will succeed, it is highly
# recommended to have Git enabled and all other changes committed before running
# this task, so that you can easily revert some or all changes if something does
# go wrong.

# Modrinth ID
raDGbHBr=raDGbHBr

# CurseForge ID (must be an integer)
833352=833352

# CurseForge Slug
tmc-framework=tmc-framework

# Mod Group
dev.terminalmc=dev.terminalmc

# GitHub Repo
TerminalMC/Framework=TerminalMC/Framework

# Owner Name
TerminalMC=TerminalMC

# Author Name
NotRyken=NotRyken

# Mod Name
Framework=Framework

# Mod ID
# Note: Neo/Forge allows '_' but not '-'
framework=framework

# Discord Invite
//discord.terminalmc.dev=//discord.terminalmc.dev

# Contact Link
//terminalmc.dev=//terminalmc.dev

# Discord ID
1103153365216669797=1103153365216669797
